/** English → Russian phrase and word mappings for i18n generation */

export const EN_TO_RU_PHRASES = [
  ["User login", "Вход пользователя"],
  ["HEMIS-integrated physical archive repository", "Репозиторий с интеграцией HEMIS и физического архива"],
  ["Digital platform for personnel and document management. Enter login and password to sign in.", "Цифровая платформа управления кадровыми и документными делами. Введите логин и пароль для входа."],
  ["After successful login, all directories will load.", "После успешного входа загрузятся все справочники."],
  ["Dashboard // General statistics", "Панель управления // Общая статистика"],
  ["Search // Document search", "Поиск // Поиск документов"],
  ["Document intake // Add new document", "Приём документов // Добавить документ"],
  ["Document list // Archive document repository", "Список документов // Хранилище архивных документов"],
  ["Categories & cabinets // System directories", "Категории и шкафы // Системные справочники"],
  ["Admin panel // Settings & audit", "Панель администратора // Настройки и аудит"],
  ["Admin panel // User management", "Панель администратора // Управление пользователями"],
  ["Number of new archive documents submitted today", "Количество новых архивных документов, принятых сегодня"],
  ["Submitted today", "Принято сегодня"],
  ["Active types linked to the archive", "Активные типы, связанные с архивом"],
  ["Active categories", "Активные категории"],
  ["Classified and placed shelves", "Классифицированные и размещённые полки"],
  ["Physical cabinets", "Физические шкафы"],
  ["TOTAL ARCHIVE DOCUMENTS", "ВСЕГО ДОКУМЕНТОВ В АРХИВЕ"],
  ["TOTAL DIGITIZED DOCUMENTS", "ВСЕГО ОЦИФРОВАННЫХ ДОКУМЕНТОВ"],
  ["System analysis & quick links", "Анализ системы и быстрые ссылки"],
  ["RECENTLY ACCEPTED DOCUMENTS", "ПОСЛЕДНИЕ ПРИНЯТЫЕ ДОКУМЕНТЫ"],
  ["NOTHING FOUND", "НИЧЕГО НЕ НАЙДЕНО"],
  ["Quick document search", "Быстрый поиск документов"],
  ["Physical search filters (AND logic)", "Фильтры физического поиска (логика И)"],
  ["Enter name or HEMIS code to search...", "Введите имя или код HEMIS для поиска..."],
  ["Select document type", "Выберите тип документа"],
  ["Select physical cabinet", "Выберите физический шкаф"],
  ["Received date (from)", "Дата приёма (с)"],
  ["Received date (to)", "Дата приёма (по)"],
  ["records", "записей"],
  ["Sorted by date (newest first)", "Отсортировано по дате (сначала новые)"],
  ["Sorting results...", "Сортировка результатов..."],
  ["Loading error", "Ошибка загрузки"],
  ["Student full name", "ФИО студента"],
  ["Student ID", "ID студента"],
  ["Document type (category)", "Тип документа (категория)"],
  ["Received date", "Дата приёма"],
  ["Physical cabinet", "Физический шкаф"],
  ["Shelf (floor)", "Полка (этаж)"],
  ["View details and PDF", "Просмотр деталей и PDF"],
  ["Print physical location voucher", "Печать ваучера физического расположения"],
  ["Archive card: ", "Архивная карта: "],
  ["Archive card:", "Архивная карта:"],
  ["Detailed document information", "Подробная информация о документе"],
  ["Accepted to archive (staff)", "Принято в архив (сотрудник)"],
  ["Received date & time", "Дата и время приёма"],
  ["Student code (ID)", "Код студента (ID)"],
  ["Academic group", "Академическая группа"],
  ["Year of birth", "Год рождения"],
  ["Contact phone", "Контактный телефон"],
  ["File details", "Сведения о файле"],
  ["Original file name", "Исходное имя файла"],
  ["View PDF document", "Просмотр PDF документа"],
  ["HIGHER EDUCATION INSTITUTION ARCHIVE", "АРХИВ ВУЗА"],
  ["PHYSICAL COPY LOCATION PRINT VOUCHER", "ВАУЧЕР ПЕЧАТИ ФИЗИЧЕСКОГО РАСПОЛОЖЕНИЯ"],
  ["Document unique code (ID)", "Уникальный код документа (ID)"],
  ["Physical location", "Физическое расположение"],
  ["Accepted to archive", "Принято в архив"],
  ["Responsible operator", "Ответственный оператор"],
  ["Administrator control center", "Центр управления администратора"],
  ["Directory and system settings", "Справочник и настройки системы"],
  ["DOCUMENT CATEGORIES", "КАТЕГОРИИ ДОКУМЕНТОВ"],
  ["ARCHIVE CABINETS (SHELVING)", "АРХИВНЫЕ ШКАФЫ (СТЕЛЛАЖИ)"],
  ["SYSTEM USERS", "ПОЛЬЗОВАТЕЛИ СИСТЕМЫ"],
  ["New document intake", "Новый приём документов"],
  ["Document repository (inventory)", "Хранилище документов (инвентаризация)"],
  ["DISTRIBUTION BY CATEGORY", "РАСПРЕДЕЛЕНИЕ ПО КАТЕГОРИЯМ"],
  ["LAST 7 DAYS INTAKE CHART", "ГРАФИК ПРИЁМА ЗА 7 ДНЕЙ"],
  ["CABINETS AND COMPLETENESS STATUS", "ШКАФЫ И СТАТУС ЗАПОЛНЕННОСТИ"],
  ["Statistics & workflow", "Статистика и активность"],
  ["Quick filter system", "Система быстрого фильтра"],
  ["PDF and physical location", "PDF и физическое расположение"],
  ["Inventory & status", "Инвентарь и статус"],
  ["Categories & cabinets", "Категории и шкафы"],
  ["Audit & accounts", "Аудит и учётные записи"],
  ["Archive cabinets", "Архивные шкафы"],
  ["This page is for searching documents in the archive.", "Эта страница предназначена для поиска документов в архиве."],
  ["General archive statistics and recent activity indicators", "Общая статистика архивной системы и показатели последней активности"],
  ["Total active documents in archive", "Всего активных документов в архиве"],
  ["Linked persons", "Связанные лица"],
  ["Active document types in system", "Активные типы документов в системе"],
  ["Physical cabinets and metal shelving", "Физические шкафы и металлические стеллажи"],
  ["New archive documents added today", "Новые архивные документы, добавленные сегодня"],
  ["percentage share", "доля в процентах"],
  ["DAILY COUNT", "ЕЖЕДНЕВНОЕ КОЛИЧЕСТВО"],
  ["click cabinet to filter", "нажмите на шкаф для фильтрации"],
  ["Capacity by floor:", "Вместимость по этажам:"],
  ["View list", "Просмотр списка"],
  ["all documents", "все документы"],
  ["Physical cabinet and shelf search: search by name, category or student code", "Поиск по физическим шкафам и полкам: ищите по имени, категории или коду студента"],
  ["Search filters", "Фильтры поиска"],
  ["Name, ID or document name", "Имя, ID или название документа"],
  ["e.g. Abduvahobov or HEMIS102938", "Например: Абдувахобов или HEMIS102938"],
  ["All", "Все"],
  ["Person / Document", "Лицо / Документ"],
  ["Found:", "Найдено:"],
  ["Manage active documents, change status, replace electronic PDF and deletion control", "Управление активными документами: редактирование, смена статуса, замена PDF и удаление"],
  ["2. Document and storage parameters", "2. Параметры документа и хранения"],
  ["Document categories and archive cabinet management", "Управление категориями документов и архивными шкафами"],
  ["Issued date & time", "Дата и время выдачи"],
  ["Printed date:", "Дата печати:"],
  ["Print error occurred: ", "Ошибка при печати: "],
  ["PHYSICAL LOCATION VOUCHER", "ВАУЧЕР ФИЗИЧЕСКОГО РАСПОЛОЖЕНИЯ"],
  ["CABINET AND SHELF COORD:", "КООРДИНАТЫ ШКАФА И ПОЛКИ:"],
  ["Note not entered", "Примечание не указано"],
  ["Shelf location description variants", "Варианты описания расположения на полке"],
  ["Staff who accepted", "Сотрудник, принявший документ"],
  ["Staff who issued document", "Сотрудник, выдавший документ"],
  ["Reload", "Перезагрузить"],
  ["PDF loading...", "Загрузка PDF..."],
  ["Download document error: ", "Ошибка при скачивании документа: "],
  ["Error loading documents", "Ошибка при загрузке документов"],
  ["Enter document name or number", "Введите название или номер документа"],
  ["Short description", "Краткое описание"],
  ["Category name", "Название категории"],
  ["Cabinet name", "Название шкафа"],
  ["Max.", "Макс."],
  ["Max. floor", "Макс. этаж"],
  ["Maximum floor", "Максимальный этаж"],
  ["e.g. 4-cabinet", "Например: 4-шкаф"],
  ["e.g. Rating register", "Например: Рейтинговая книга"],
  ["Select existing student!", "Выберите существующего студента!"],
  ["Select existing student", "Выбор существующего студента"],
  ["Directory and system settings", "Справочник и настройки системы"],
  ["New category", "Новая категория"],
  ["New cabinet", "Новый шкаф"],
  ["Last name and first name required for new student", "Для нового студента обязательны фамилия и имя"],
  ["Update", "Обновить"],
  ["Staff ID number required", "Обязателен ID номер сотрудника"],
  ["-- Select student --", "-- Выберите студента --"],
  ["Voucher", "Ваучер"],
  ["Type", "Тип"],
  ["Name", "Название"],
  ["Description", "Описание"],
  ["Phone", "Телефон"],
  ["Date", "Дата"],
  ["Category", "Категория"],
  ["Document", "Документ"],
  ["documents", "документов"],
  ["User", "Пользователь"],
  ["Yes", "Да"],
  ["Cancel", "Отмена"],
  ["Optional", "Необязательно"],
  ["Active", "Активный"],
  ["Location", "Расположение"],
  ["Location description", "Описание расположения"],
  ["Document type:", "Тип документа:"],
  ["Review final information", "Проверка итоговой информации"],
  ["Final summary — check before saving", "Итоговое резюме — проверьте перед сохранением"],
  ["Category selection", "Выбор категории"],
  ["Document data", "Данные документа"],
  ["PDF copy", "PDF копия"],
  ["Archive location", "Архивное расположение"],
  ["Summary and save", "Итог и сохранение"],
  ["Select field department", "Выберите отдел сферы"],
  ["Title, purpose and year of issue", "Название, назначение и год выпуска"],
  ["Maximum size: 30 MB (.pdf)", "Максимальный размер: 30 МБ (.pdf)"],
  ["Cabinet and shelf", "Шкаф и полка"],
  ["Final data verification", "Проверка итоговых данных"],
  ["mandatory", "обязательно"],
  ["Select category", "Выберите категорию"],
  ["Description not entered", "Описание не указано"],
  ["Select", "Выбрать"],
  ["Complex student data, PDF upload and physical storage coordinates registration", "Комплексный ввод данных студента, загрузка PDF и регистрация координат физического хранения"],
  ["New document intake (Intake)", "Новый приём документов"],
  ["Sunday", "Вс"],
  ["Monday", "Пн"],
  ["Tuesday", "Вт"],
  ["Wednesday", "Ср"],
  ["Thursday", "Чт"],
  ["Friday", "Пт"],
  ["Saturday", "Сб"],
];

export const EN_TO_RU_WORDS = [
  ["Documents", "Документы"], ["Document", "Документ"], ["documents", "документов"], ["document", "документ"],
  ["Archive", "Архив"], ["archive", "архив"], ["To archive", "В архив"], ["From archive", "Из архива"],
  ["Search", "Поиск"], ["search", "поиск"],
  ["Category", "Категория"], ["Categories", "Категории"], ["category", "категория"],
  ["Cabinet", "Шкаф"], ["Cabinets", "Шкафы"], ["cabinet", "шкаф"], ["cabinets", "шкафы"],
  ["Student", "Студент"], ["Students", "Студенты"], ["student", "студент"],
  ["Staff", "Сотрудник"], ["staff", "сотрудник"],
  ["Save", "Сохранить"], ["save", "сохранить"], ["Saving", "Сохранение"],
  ["Delete", "Удалить"], ["delete", "удалить"], ["Deleted", "Удалён"],
  ["Edit", "Редактировать"], ["edit", "редактировать"],
  ["View", "Просмотр"], ["view", "просмотр"], ["Details", "Подробности"],
  ["Upload", "Загрузка"], ["upload", "загрузка"], ["Uploaded", "Загружено"],
  ["Filter", "Фильтр"], ["Filters", "Фильтры"], ["filter", "фильтр"],
  ["Management", "Управление"], ["management", "управление"],
  ["panel", "панель"], ["Panel", "Панель"],
  ["System", "Система"], ["system", "система"],
  ["Status", "Статус"], ["status", "статус"],
  ["Date", "Дата"], ["date", "дата"],
  ["Note", "Примечание"], ["note", "примечание"],
  ["Description", "Описание"], ["description", "описание"],
  ["Name", "Название"], ["name", "название"],
  ["Number", "Номер"], ["number", "номер"],
  ["Floor", "Этаж"], ["floor", "этаж"],
  ["Location", "Расположение"], ["location", "расположение"],
  ["Physical", "Физическое"], ["physical", "физическое"],
  ["Active", "Активный"], ["active", "активный"], ["Inactive", "Неактивный"],
  ["New", "Новый"], ["new", "новый"], ["Latest", "Последний"],
  ["Today", "Сегодня"], ["today", "сегодня"],
  ["All", "Все"], ["all", "все"],
  ["Found", "Найдено"], ["found", "найдено"], ["Not found", "Не найдено"],
  ["Success", "Успех"], ["Error", "Ошибка"], ["error", "ошибка"],
  ["Loading", "Загрузка"], ["loading", "загрузка"],
  ["Data", "Данные"], ["data", "данные"],
  ["Intake", "Приём"], ["intake", "приём"],
  ["Group", "Группа"], ["group", "группа"],
  ["Last name", "Фамилия"], ["First name", "Имя"],
  ["Position", "Должность"], ["Department", "Отдел"],
  ["Phone", "Телефон"], ["phone", "телефон"],
  ["File", "Файл"], ["file", "файл"],
  ["Maximum", "Максимальный"], ["maximum", "максимальный"],
  ["e.g.", "Например"], ["select", "выберите"], ["Select", "Выберите"],
  ["add", "добавить"], ["Add", "Добавить"],
  ["list", "список"], ["List", "Список"],
  ["Statistics", "Статистика"], ["statistics", "статистика"],
  ["Inventory", "Инвентарь"], ["inventory", "инвентарь"],
  ["Repository", "Хранилище"], ["repository", "хранилище"],
  ["directory", "справочник"], ["Directory", "Справочник"],
  ["Audit", "Аудит"], ["audit", "аудит"],
  ["Log", "Журнал"], ["log", "журнал"],
  ["Institute", "Институт"], ["institute", "институт"],
  ["required", "обязательно"], ["Optional", "Необязательно"],
  ["Back", "Назад"], ["Next", "Далее"], ["Page", "Страница"],
  ["Log out", "Выйти"], ["Close", "Закрыть"], ["Print", "Печать"],
  ["Cancel", "Отмена"], ["Clear", "Очистить"],
  ["Not entered", "Не указано"], ["Unknown", "Неизвестно"],
  ["Processing", "Обработка"],
  ["Please", "Пожалуйста"], ["please", "пожалуйста"],
  ["an error occurred", "произошла ошибка"],
  ["not found", "не найдено"], ["not available", "недоступно"],
  ["not entered", "не указано"], ["entered", "введено"],
  ["selected", "выбрано"], ["accepted", "принято"],
  ["change", "изменить"], ["changed", "изменено"],
  ["confirm", "подтвердить"], ["I confirm", "Подтверждаю"],
  ["all rights reserved", "все права защищены"],
  ["In place", "На месте"], ["Issued", "Выдан"],
  ["items", "шт."], ["records", "записей"],
  ["Actions", "Действия"], ["actions", "действия"],
  ["Operator", "Оператор"], ["Administrator", "Администратор"],
  ["Viewer", "Наблюдатель"], ["Password", "Пароль"], ["Username", "Имя пользователя"],
  ["Sign in", "Войти"], ["Dashboard", "Панель управления"],
  ["Download", "Скачать"], ["download", "скачать"],
  ["Type", "Тип"], ["type", "тип"],
  ["Yes", "Да"], ["No", "Нет"],
  ["User", "Пользователь"], ["Users", "Пользователи"], ["user", "пользователь"],
  ["Voucher", "Ваучер"], ["voucher", "ваучер"],
  ["Reload", "Перезагрузить"], ["Update", "Обновить"],
  ["Total", "Всего"], ["total", "всего"],
  ["Linked", "Связанные"], ["linked", "связанные"],
  ["persons", "лица"], ["Person", "Лицо"], ["person", "лицо"],
  ["workflow", "активность"], ["share", "доля"],
  ["shelf", "полка"], ["Shelf", "Полка"],
  ["shelving", "стеллажи"], ["metal", "металлические"],
  ["control", "управление"], ["settings", "настройки"],
  ["accounts", "учётные записи"], ["account", "аккаунт"],
  ["certified", "сертифицирована"], ["Security", "Безопасность"],
  ["Management System", "Система управления"],
  ["Chief archivist (Admin)", "Главный архивариус (Админ)"],
  ["Archive operator", "Оператор архива"],
  ["Archivist (Viewer)", "Архивариус (просмотр)"],
  ["Document management system", "Система управления документами"],
  ["Enter your credentials to access the archive", "Введите данные для доступа к архивному аккаунту"],
  ["Please fill in all fields", "Пожалуйста, заполните все поля"],
  ["An error occurred while signing in", "Ошибка при входе в систему"],
  ["Archive. All rights reserved.", "Архив. Все права защищены."],
  ["FJSTI Archive", "Архив FJSTI"],
];

function applyPhrases(text, phrases) {
  if (!text) return text;
  let result = text;
  const sorted = [...phrases].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of sorted) {
    if (result.includes(from)) result = result.split(from).join(to);
  }
  return result;
}

function applyWords(text, words) {
  let result = text;
  const sorted = [...words].sort((a, b) => b[0].length - a[0].length);
  for (const [from, to] of sorted) {
    result = result.split(from).join(to);
  }
  return result;
}

const EN_TO_RU_CACHE = new Map();

export function enToRu(en) {
  if (!en) return en;
  if (EN_TO_RU_CACHE.has(en)) return EN_TO_RU_CACHE.get(en);

  let result = applyPhrases(en, EN_TO_RU_PHRASES);
  if (result !== en) {
    EN_TO_RU_CACHE.set(en, result);
    return result;
  }
  result = applyWords(en, EN_TO_RU_WORDS);
  EN_TO_RU_CACHE.set(en, result);
  return result;
}

/** Uzbek-specific Cyrillic letters — if present, translation is incomplete */
const UZ_CYRL_RE = /[ЎўҒғҚқҲҳ]/;

export function isBadRussian(text) {
  return UZ_CYRL_RE.test(text) || /\b(шт\.н|сшт\.|данныеи|тизими|қидирув|ҳужжат)\b/i.test(text);
}
